name: bowphp-docs

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        php-version: [8.2]
        os: [ubuntu-latest]
    name: build php-${{ matrix.php-version }} / node-${{ matrix.node-version }} on ${{ matrix.os }}
  
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, mysql, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i --legacy-peer-deps
      - run: npm run build --if-present
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: build
          recursive: true
          remote: bowphp.com
          host: ${{ secrets.BOWPHP_WEBSITE_REMOTE_HOST }}
          username: ${{ secrets.BOWPHP_WEBSITE_REMOTE_USER }}
          password: ${{ secrets.BOWPHP_WEBSITE_REMOTE_PASSWORD }}
